# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Idpishield < Formula
  desc "Defense against Indirect Prompt Injection (IDPI) attacks for AI agents"
  homepage "https://github.com/pinchtab/idpishield"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pinchtab/idpishield/releases/download/v0.1.2/idpishield-darwin-amd64"
      sha256 "f5fd70f5e683405b10bf5d3efd1a9385ab253cc1b46dfd9e4b5e719195f1e5c6"

      define_method(:install) do
        bin.install Dir["idpishield*"].first => "idpishield"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pinchtab/idpishield/releases/download/v0.1.2/idpishield-darwin-arm64"
      sha256 "9f3151229151e689dfdde6588a15e23f7bfdf3c6e76999387c776f4ba513b753"

      define_method(:install) do
        bin.install Dir["idpishield*"].first => "idpishield"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pinchtab/idpishield/releases/download/v0.1.2/idpishield-linux-amd64"
      sha256 "457e1140310f1f93c951678f495af94503606ebc968bfc070a69c210f171054d"
      define_method(:install) do
        bin.install Dir["idpishield*"].first => "idpishield"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pinchtab/idpishield/releases/download/v0.1.2/idpishield-linux-arm64"
      sha256 "3901740cb9323a8cc0901b7d9931e8b33a2086b7ccf37cc9399559400cd8d123"
      define_method(:install) do
        bin.install Dir["idpishield*"].first => "idpishield"
      end
    end
  end

  test do
    system "#{bin}/idpishield", "help"
  end
end
