# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Idpishield < Formula
  desc "Defense against Indirect Prompt Injection (IDPI) attacks for AI agents"
  homepage "https://github.com/pinchtab/idpishield"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pinchtab/idpishield/releases/download/v0.1.4/idpishield-darwin-amd64"
      sha256 "c596415ef46b99830db42ec3dfaf5a9eec8c5bcbd08def9eef77b00b9f275c4e"

      define_method(:install) do
        bin.install Dir["idpishield*"].first => "idpishield"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pinchtab/idpishield/releases/download/v0.1.4/idpishield-darwin-arm64"
      sha256 "c6e2cfdb8956e44eae283681f7da1741d56fa3debaf1ef2f4247b30afb60b940"

      define_method(:install) do
        bin.install Dir["idpishield*"].first => "idpishield"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pinchtab/idpishield/releases/download/v0.1.4/idpishield-linux-amd64"
      sha256 "565fc2ce00ecef4e8c5627635b811091c397fee81959955a99498ebef99e4af5"
      define_method(:install) do
        bin.install Dir["idpishield*"].first => "idpishield"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pinchtab/idpishield/releases/download/v0.1.4/idpishield-linux-arm64"
      sha256 "6b6713ba35b6a495cb1e0df65392aa6b6d5d13ff6ed7fb66251d806ebe162a51"
      define_method(:install) do
        bin.install Dir["idpishield*"].first => "idpishield"
      end
    end
  end

  test do
    system "#{bin}/idpishield", "help"
  end
end
