# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class IdpiShield < Formula
  desc "Defense against Indirect Prompt Injection (IDPI) attacks for AI agents"
  homepage "https://github.com/pinchtab/idpishield"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pinchtab/idpishield/releases/download/v0.1.0/idpi-shield-darwin-amd64"
      sha256 "de60d82a26c5f12bbdcf18187e513c096525679e4b4ce26e5be126cfc2af7969"

      define_method(:install) do
        bin.install Dir["idpi-shield*"].first => "idpi-shield"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pinchtab/idpishield/releases/download/v0.1.0/idpi-shield-darwin-arm64"
      sha256 "0923cd6f6ff2204e97b00ee8b19cbe9c00db367b7abc263b71e71176cb94ab30"

      define_method(:install) do
        bin.install Dir["idpi-shield*"].first => "idpi-shield"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pinchtab/idpishield/releases/download/v0.1.0/idpi-shield-linux-amd64"
      sha256 "7de8172aaba8a07b238189251dee8796ebb835b94ab253fa1ec61d54f14bf0f9"
      define_method(:install) do
        bin.install Dir["idpi-shield*"].first => "idpi-shield"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pinchtab/idpishield/releases/download/v0.1.0/idpi-shield-linux-arm64"
      sha256 "81b2f609a81501124eb9f92de3a8bb2aa9a1a7757bd39b1ad1025b832f20f9bd"
      define_method(:install) do
        bin.install Dir["idpi-shield*"].first => "idpi-shield"
      end
    end
  end

  test do
    system "#{bin}/idpi-shield", "help"
  end
end
