# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pinchtab < Formula
  desc "High-performance browser automation bridge and multi-instance orchestrator for AI agents"
  homepage "https://pinchtab.com"
  version "0.13.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pinchtab/pinchtab/releases/download/v0.13.1/pinchtab-darwin-amd64"
      sha256 "3e9bd1cec1e25fa0ce57d3a5eae71f8c9084029c0cf454c21f11cd16d9cfcd9c"

      define_method(:install) do
        bin.install Dir["pinchtab*"].first => "pinchtab"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pinchtab/pinchtab/releases/download/v0.13.1/pinchtab-darwin-arm64"
      sha256 "da210b35b355c01800d16d21d11d06e61201de350487c827f9d463bbffe46e48"

      define_method(:install) do
        bin.install Dir["pinchtab*"].first => "pinchtab"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pinchtab/pinchtab/releases/download/v0.13.1/pinchtab-linux-amd64"
      sha256 "63ce7808830414a2fe5248d831e82ba16865338c8e387567fdbbf0544902525a"
      define_method(:install) do
        bin.install Dir["pinchtab*"].first => "pinchtab"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pinchtab/pinchtab/releases/download/v0.13.1/pinchtab-linux-arm64"
      sha256 "8de374c557558b1baf27eb83f4c28ddae51eb2bafac23326bdf73d24c39badcc"
      define_method(:install) do
        bin.install Dir["pinchtab*"].first => "pinchtab"
      end
    end
  end

  test do
    system "#{bin}/pinchtab version"
  end
end
