# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pinchtab < Formula
  desc "High-performance browser automation bridge and multi-instance orchestrator for AI agents"
  homepage "https://pinchtab.com"
  version "0.14.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pinchtab/pinchtab/releases/download/v0.14.1/pinchtab-darwin-amd64"
      sha256 "b3974adadac13aee6d4b471aba4db4cd9668a71c49f85fb9525fc07f19545212"

      define_method(:install) do
        bin.install Dir["pinchtab*"].first => "pinchtab"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pinchtab/pinchtab/releases/download/v0.14.1/pinchtab-darwin-arm64"
      sha256 "0aa406b02def05617cfa5bb3aad8e96984526ad03ea21f30769719ec7b9d2d6b"

      define_method(:install) do
        bin.install Dir["pinchtab*"].first => "pinchtab"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pinchtab/pinchtab/releases/download/v0.14.1/pinchtab-linux-amd64"
      sha256 "f9433ba78646757ef390ba72c18e26360337050635c1ddba471fb11a72c57122"
      define_method(:install) do
        bin.install Dir["pinchtab*"].first => "pinchtab"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pinchtab/pinchtab/releases/download/v0.14.1/pinchtab-linux-arm64"
      sha256 "30e7c0cceed7a95c24855a21c3905fbcd2546d83c556d0d055669c0def3f22f0"
      define_method(:install) do
        bin.install Dir["pinchtab*"].first => "pinchtab"
      end
    end
  end

  test do
    system "#{bin}/pinchtab version"
  end
end
