# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Seaportal < Formula
  desc "HTTP-first web content extraction for AI agents: Markdown, accessibility snapshots, sitemap/feed parsing, and an MCP server"
  homepage "https://github.com/pinchtab/seaportal"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pinchtab/seaportal/releases/download/v0.2.0/seaportal-darwin-amd64"
      sha256 "37d2aa993c2fe0ce019c67d399d7b410bec23ce1a7e0a4ca344aa673a7e49337"

      define_method(:install) do
        bin.install Dir["seaportal*"].first => "seaportal"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pinchtab/seaportal/releases/download/v0.2.0/seaportal-darwin-arm64"
      sha256 "1357d5393ee487edcf6423f3c5f5c43e669c3d1c7a380ab15e6603603f3d305f"

      define_method(:install) do
        bin.install Dir["seaportal*"].first => "seaportal"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pinchtab/seaportal/releases/download/v0.2.0/seaportal-linux-amd64"
      sha256 "b1e738514a1abd9b892613de08fbd230fc3a3afdf356e3437fde47ecb3130432"
      define_method(:install) do
        bin.install Dir["seaportal*"].first => "seaportal"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pinchtab/seaportal/releases/download/v0.2.0/seaportal-linux-arm64"
      sha256 "3ef93acc74eb820a1ce323333ed81a93d4f99e2c1dd9ce907135b8dc1e3d0b0f"
      define_method(:install) do
        bin.install Dir["seaportal*"].first => "seaportal"
      end
    end
  end

  test do
    system "#{bin}/seaportal", "--version"
  end
end
