# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Seaportal < Formula
  desc "HTTP-first web content extraction for AI agents: Markdown, accessibility snapshots, sitemap/feed parsing, and an MCP server"
  homepage "https://github.com/pinchtab/seaportal"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pinchtab/seaportal/releases/download/v0.1.1/seaportal-darwin-amd64"
      sha256 "32e7bd113a70ac21da216a25dd2e08cd3e2c16b04a5ff37c1cca6010436604cb"

      define_method(:install) do
        bin.install Dir["seaportal*"].first => "seaportal"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pinchtab/seaportal/releases/download/v0.1.1/seaportal-darwin-arm64"
      sha256 "2f4b2ff5ec4e8298d9dddd529aea1cd4d665b8419387c455273142b5dca7dadb"

      define_method(:install) do
        bin.install Dir["seaportal*"].first => "seaportal"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pinchtab/seaportal/releases/download/v0.1.1/seaportal-linux-amd64"
      sha256 "838d00a23634b231dc44feab02892cf903117e19ce5eb322b5d227386fa2d7b6"
      define_method(:install) do
        bin.install Dir["seaportal*"].first => "seaportal"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pinchtab/seaportal/releases/download/v0.1.1/seaportal-linux-arm64"
      sha256 "def30af59aaffb99ef9478bb9ef4a525d22bc4bafac7b5e2a9368953263b85d3"
      define_method(:install) do
        bin.install Dir["seaportal*"].first => "seaportal"
      end
    end
  end

  test do
    system "#{bin}/seaportal", "--version"
  end
end
