# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Semantic < Formula
  desc "Zero-dependency semantic matching for accessibility tree elements"
  homepage "https://github.com/pinchtab/semantic"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pinchtab/semantic/releases/download/v0.1.1/semantic-darwin-amd64"
      sha256 "12fa08df7e337701c152614a7796f27d9ff23aa89856868a2db2ef49a284f839"

      define_method(:install) do
        bin.install Dir["semantic*"].first => "semantic"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pinchtab/semantic/releases/download/v0.1.1/semantic-darwin-arm64"
      sha256 "7c20b812d372ef9dcee0261eb957974b500881077dfef87bf774db2d13922caf"

      define_method(:install) do
        bin.install Dir["semantic*"].first => "semantic"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pinchtab/semantic/releases/download/v0.1.1/semantic-linux-amd64"
      sha256 "086150775ecff9f0197e9410effc0e2a9bcbb67cdab972e9a4d75a81b28c03a5"
      define_method(:install) do
        bin.install Dir["semantic*"].first => "semantic"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pinchtab/semantic/releases/download/v0.1.1/semantic-linux-arm64"
      sha256 "025c7c2669b43b048aac4af24945ee56bcfd0715951c00263c13dce5f8ea9ee7"
      define_method(:install) do
        bin.install Dir["semantic*"].first => "semantic"
      end
    end
  end

  test do
    system "#{bin}/semantic version"
  end
end
