# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Semantic < Formula
  desc "Zero-dependency semantic matching for accessibility tree elements"
  homepage "https://github.com/pinchtab/semantic"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pinchtab/semantic/releases/download/v0.1.0/semantic-darwin-amd64"
      sha256 "341e228cf466ce7b7a1a80f94aea644caebec856d8dea5fd6de1d6924fb35bdd"

      define_method(:install) do
        bin.install Dir["semantic*"].first => "semantic"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pinchtab/semantic/releases/download/v0.1.0/semantic-darwin-arm64"
      sha256 "1143ebbe5321f37ec45dea7fb6e86382a73f4e35ab8949451159b7410105ffbf"

      define_method(:install) do
        bin.install Dir["semantic*"].first => "semantic"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pinchtab/semantic/releases/download/v0.1.0/semantic-linux-amd64"
      sha256 "837ab4104e11978a5b1258287f33b80c35abb67ca11efa850307286885df0d06"
      define_method(:install) do
        bin.install Dir["semantic*"].first => "semantic"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pinchtab/semantic/releases/download/v0.1.0/semantic-linux-arm64"
      sha256 "3be8b19532284e66c6dd9224316571f2b4a7a5e1040567db91964bb0cce1093c"
      define_method(:install) do
        bin.install Dir["semantic*"].first => "semantic"
      end
    end
  end

  test do
    system "#{bin}/semantic version"
  end
end
